### ISSUE TITLE
How to Use SFTP with SSH?

### ISSUE THREAD

**Issue by hrsetyono** [sebastianpopp/git-ftp-action#14]
Hi,

I'm wondering how to use SSH authentication. In [git-ftp documentation](https://github.com/git-ftp/git-ftp/blob/1.6.0/man/git-ftp.1.md#options) it says to use `--key` options and specify the file.

But how do we specify file path in Github Action?

Thank you

**Comment by sebastianpopp** [comment]
You can pass additional options via `options`. You might want to use the `fix-ssl-issue`-branch because SFTP doesn't work with the current v3 release. But I'm actually not sure how to handle the `password`-parameter. It would probably need to become an optional parameter. Right now it's required and always passed to the command.

**Comment by hrsetyono** [comment]
Hi @sebastianpopp 

Thank you for your reply.

Yes, I tried adding `--key` via options but keep getting error saying that the password is required. Maybe because the `--passwd` option is hardcoded in entrypoint?

Is the `fix-ssl-issue` working? It still has the `--passwd` option.

Also I have forked your repo trying to test this (https://github.com/hrsetyono/git-sftp-action). I have published it in marketplace.

But whenever I'm using it, I get 404 error with this message:

```
##[error]An action could not be found at the URI 'https://api.github.com/repos/hrsetyono/git-sftp-action/tarball/v4'
```

Does it take long time for the marketplace to add new action?

**Comment by sebastianpopp** [comment]
No, you'll still have to remove the password (or better: make it optional, so the action works both ways). The `fix-ssl-issue`-branch just uses a prebuilt docker image, that has curl with ssh support (Alpine, unfortunately, doesn't have support built-in, see #13).
You don't need to publish your Action on the marketplace to use it. From the error message, it looks like you're just referencing a non-existant branch `v4`.

**Comment by hrsetyono** [comment]
Hi @sebastianpopp 

I've just tested the `fix-ssl-issue` branch. But how do you remove the password option?

Removing the `password` in workflow will cause this error:

```
fatal: Too few arguments for option -p.
```

But if I leave it as empty string `password: ""` then I got the wrong password error.

Sorry for the trouble

**Comment by sebastianpopp** [comment]
That the password parameter is required is defined [here](https://github.com/sebastianpopp/git-ftp-action/blob/master/action.yml#L13). If you set that to `false` and handle the missing parameter in the `entrypoint.sh`, it should work.

**Comment by hrsetyono** [comment]
Thanks for the help so far. I just had one more problem. I'm not sure how to include the private key to `--key` option

From my finding, I need to echo it to a file first, then use that file in `--key`?

Here's my workflow:

```
name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: 'echo "$SSH_KEY" > the_key'
      shell: bash
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name: git-ftp catchup
      uses: sebastianpopp/git-ftp-action@fix-ssl-issue
      with:
        url: "mydomain.com/home/mysite"
        user: ${{ secrets.DO_USERNAME }}
        password: false
        options: "--key /the_key --auto-init"
```

That workflow will make me stuck loading at this line:

```
Run sebastianpopp/git-ftp-action@fix-ssl-issue
/usr/bin/docker run --name sebastianpoppgitftpactionfixsslissue_69d9ee --label 3888d3 --workdir /github/workspace --rm -e INPUT_URL -e INPUT_USER -e INPUT_PASSWORD -e INPUT_OPTIONS -e INPUT_SYNCROOT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/myrepo/myrepo":"/github/workspace" sebastianpopp/git-ftp-action:fix-ssl-issue
```

I'm assuming I include the key in a wrong way?

**Comment by sebastianpopp** [comment]
I think you need to lose the leading slash before `the_key`. The key should be in your working directory which should be automatically set inside the docker container. Not sure why it's just stuck without an error message tho.

**Comment by hrsetyono** [comment]
I tried without leading slash and stuck in the same place.

Do you mean I should upload the private key into my repo? I think that's going to be a security risk.

**Comment by hrsetyono** [comment]
Hi, So I found the solution which is to give up on using SSH Key and simply use Password

It needs `--insecure` option too. I'm honestly not sure how dangerous that is.

```
name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@fix-ssl-issue
      with:
        url: "sftp://123.45.67.89/~/path/"
        user: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        options: "--auto-init --insecure"
```

**Comment by hdwebpros** [comment]
I'm using this right now:
```
      - name: Deploy to Live Server
        if: github.ref == 'refs/heads/main'
        uses: sebastianpopp/git-ftp-action@fix-ssl-issue
        with:
          url: sftp://${{ secrets.FTP_ADDRESS_LIVE }}
          user: ${{ secrets.FTP_USER_LIVE }}
          password: ${{ secrets.FTP_PASSWORD_LIVE }}
          options: '--auto-init --force --changed-only --insecure -vv --remote-root public_html'
```

But that produces this output
```
Thu May 11 14:24:03 UTC 2023: git-ftp version 1.6.0 running on Linux da379408e023 5.15.0-[10](https://github.com/Happy-Dog-Web-Productions/mn4wda.org/actions/runs/4948972440/jobs/8850436732#step:6:11)37-azure #44-Ubuntu SMP Thu Apr 20 13:19:31 UTC 2023 x86_64 Linux
Thu May [11](https://github.com/Happy-Dog-Web-Productions/mn4wda.org/actions/runs/4948972440/jobs/8850436732#step:6:12) [14](https://github.com/Happy-Dog-Web-Productions/mn4wda.org/actions/runs/4948972440/jobs/8850436732#step:6:15):24:03 UTC 2023: Using syncroot . if exists.
Thu May 11 14:24:03 UTC 2023: Auto init if needed.
Thu May 11 14:24:03 UTC 2023: Forced mode enabled.
Thu May 11 14:24:03 UTC 2023: Downloading only changed files.
Thu May 11 14:24:03 UTC 2023: Insecure SSL/TLS connection allowed
Thu May 11 14:24:03 UTC 2023: Syncroot is './'.
Thu May 11 14:24:03 UTC 2023: Host is '***'.
Thu May 11 14:24:03 UTC 2023: User is '***'.
Thu May 11 14:24:03 UTC 2023: Password is set.
Thu May 11 14:24:03 UTC 2023: CACert is ''.
Thu May 11 14:24:03 UTC 2023: Insecure is '1'.
Thu May 11 14:24:03 UTC 2023: Proxy is ''.
Thu May 11 14:24:03 UTC 2023: Path is 'public_html/'.
Thu May 11 14:24:03 UTC 2023: The remote sha1 is saved in file '.git-ftp.log'.
Thu May 11 14:24:03 UTC 2023: Check if curl is functional.
Thu May 11 14:24:03 UTC 2023: Retrieving last commit from ***/public_html/.
*   Trying 184.[16](https://github.com/***********/actions/runs/4948972440/jobs/8850436732#step:6:17)8.47.225:22...
* Connected to *** ([18](https://github.com/***********/actions/runs/4948972440/jobs/8850436732#step:6:19)4.168.47.225) port 22 (#0)
* Failure establishing ssh session: -43, Failed getting banner
#=#=#                                                                         
* Closing connection 0
curl: (2) Failure establishing ssh session: -43, Failed getting banner

Thu May 11 14:24:03 UTC [20](https://github.com/**********/actions/runs/4948972440/jobs/8850436732#step:6:21)23: Check if *** is accessible.
#=#=#                                                                         
*   Trying 184.168.47.[22](https://github.com/*************/actions/runs/4948972440/jobs/8850436732#step:6:23)5:22...
* Connected to *** (184.168.47.225) port 22 (#0)
##O#-#                                                                        
* SSH MD5 fingerprint: **********************
* SSH authentication methods available: publickey,password
* Using SSH private key file ''
* SSH public key authentication failed: Unable to extract public key from private key file: Unable to open private key file
##O=#  #                                                                      
* Initialized password authentication
* Authentication complete
#=#=-#  #                                                                     
* Could not open directory for reading: No such file or directory
* Connection #0 to host *** left intact
curl: (78) Could not open directory for reading: No such file or directory

Thu May 11 14:24:03 UTC 20[23](https://github.com/*******/actions/runs/4948972440/jobs/8850436732#step:6:24): Create public_html/
*   Trying 184.168.47.225:22...
* Connected to *** (184.xxx.xx.xxx) port 22 (#0)
#=#=#                                                                         
* SSH MD5 fingerprint: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
* SSH authentication methods available: publickey,password
* Using SSH private key file ''
* SSH public key authentication failed: Unable to extract public key from private key file: Unable to open private key file
* Initialized password authentication
* Authentication complete
##O#-#                                                                        
##O=#  #                                                                      
* Sending quote commands
* Could not open directory for reading: No such file or directory
* Connection #0 to host *** left intact
curl: (78) Could not open directory for reading: No such file or directory

Thu May 11 14:[24](https://github.com/*************/actions/runs/4948972440/jobs/8850436732#step:6:25):04 UTC 2023: fatal:  The resource does not exist. exiting...
```

I redacted some of the information, but you should see the point.

The thing is, I'm using the same login credentials in Filezilla as SFTP and it works just fine. But git-ftp doesn't seem to work

**Comment by hrsetyono** [comment]
@hdwebpros Have you tried my configuration above? It's been working well for me on both DigitalOcean and in a managed hosting.

**Comment by hdwebpros** [comment]
False alarm... I'm an idiot and had the wrong path

**Comment by Plagiatus** [comment]
I keep getting `Can't access remote '***'. Network down? Wrong URL? exiting...` as the error message. I triple checked the URL to be correct, same for the username and password. And I can connect just fine from my local computer using winscp.

I'm thankful for any ideas.

here is my config:
```yml
- name: Sync files 📁
  uses: sebastianpopp/git-ftp-action@fix-ssl-issue
  with:
    url: sftp://${{ secrets.ftp_server }}
    user: ${{ secrets.ftp_username }}
    password: ${{ secrets.ftp_password }}
    options: "--auto-init --remote-root world"
```

_PS: I've been using ftp-action for a lot of my repositories, it's great. I came here in search for help with an sftp action, as using the ftp-action for that would just stall forever._
