### ISSUE TITLE
Git FTP fails to verify server fingerprint

### ISSUE THREAD

**Issue by NathanBlennd** [sebastianpopp/git-ftp-action#6]
I'm trying to use SFTP and it's failing due to not being able to verify the server fingerprint. I've verified this by manually running git ftp push with the --insecure flag and it works as intended.

Is there anyway that the --ignore flag could be implemented? Or better yet, a way to verify the server fingerprint?

**Comment by sebastianpopp** [comment]
Thanks for the suggestion. I added an `options` input parameter so now you can do something like this:

```
name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://ftp.example.com/path/"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
        options: "--auto-init --insecure"
```
